applications:
  - name: django-app
    project: default

    source:
      repoURL: https://github.com/slonic32/my-microservice-project.git
      path: Progect/charts/django-app
      targetRevision: main

      helm:
        valueFiles:
          - values.yaml

        parameters:
          - name: image.repository
            value: "${ecr_repository_url}"

    destination:
      server: https://kubernetes.default.svc
      namespace: django

    syncPolicy:
      automated:
        prune: true
        selfHeal: true

      syncOptions:
        - CreateNamespace=true

repositories: []

repoConfig:
  insecure: "false"
  enableLfs: "true"