controller:
  admin:
    username: admin
    createSecret: false
    existingSecret: jenkins-admin-credentials
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password

  serviceType: LoadBalancer
  servicePort: 80

  probes:
    startupProbe:
      failureThreshold: 60
      periodSeconds: 10
      timeoutSeconds: 10

    livenessProbe:
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 5

    readinessProbe:
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 5

  containerEnv:
    - name: GITHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: github-credentials
          key: GITHUB_USERNAME

    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-credentials
          key: GITHUB_TOKEN

  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - credentials-binding:latest
    - github:latest
    - job-dsl:latest


  JCasC:
    configScripts:
      github-credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      scope: GLOBAL
                      id: github-token
                      username: "${GITHUB_USERNAME}"
                      password: "${GITHUB_TOKEN}"
                      description: "GitHub credential for Jenkins CI/CD"

      seed-job: |
        jobs:
          - script: >
              pipelineJob("goit-django-docker") {
                triggers {
                  scm("H/5 * * * *")
                }

                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url("https://github.com/slonic32/my-microservice-project.git")
                          credentials("github-token")
                        }
                        branches("*/main")
                      }
                    }

                    scriptPath("django/Jenkinsfile")
                  }
                }
              }

persistence:
  enabled: true
  storageClass: "ebs-sc"
  size: 10Gi

serviceAccount:
  name: jenkins-sa
  create: false