image:
  repository: "set-by-argo-cd"
  tag: "v1.0.4"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

config:
  ALLOWED_HOSTS: "localhost,127.0.0.1,nginx,django,.eu-central-1.elb.amazonaws.com"

existingSecret: django-app-secret

probes:
  liveness:
    path: /admin/login/
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readiness:
    path: /admin/login/
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
