grafana:
  enabled: true

  fullnameOverride: grafana

  service:
    type: ClusterIP
    port: 80

  persistence:
    enabled: true
    storageClassName: ebs-sc
    accessModes:
      - ReadWriteOnce
    size: 5Gi

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "300m"
      memory: "512Mi"

prometheus:
  enabled: true

  prometheusSpec:
    retention: 7d

    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-sc
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

alertmanager:
  enabled: true

  alertmanagerSpec:
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true
